# Generated by Django 6.0.2 on 2026-03-04 12:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description_de',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='specs_de',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='specs_en',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
