# Generated by Django 6.0.2 on 2026-03-05 09:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_description_de_alter_car_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(default='About Our Dealership', max_length=200)),
                ('title_de', models.CharField(default='Über unser Autohaus', max_length=200)),
                ('content_en', ckeditor.fields.RichTextField()),
                ('content_de', ckeditor.fields.RichTextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Content',
            },
        ),
    ]
